baseURL = 'https://the-raccoon-way.de/'
languageCode = 'de'
defaultContentLanguage = 'de'
title = 'The Raccoon Way'
theme = 'PaperMod'
paginate = 10

[params]
  author = 'Daniela Zurwerra'
  description = 'From No-Code to No-Limits'
  keywords = ['Power Platform', 'Power Automate', 'Low Code', 'Automatisierung']
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  defaultTheme = 'auto'

  [params.analytics.umami]
    websiteID = 'af09530a-757f-4427-ac84-f5f3452f3000'
    jsURL = 'https://cloud.umami.is/script.js'

  [params.profileMode]
    enabled = true
    title = 'The Raccoon Way'
    subtitle = 'From No-Code to No-Limits'
    imageUrl = '/images/Raccoon-Sticker.png'
    imageWidth = 200
    imageHeight = 200
    imageTitle = 'The Raccoon Way'
    [[params.profileMode.buttons]]
      name = 'Blog'
      url = '/posts'

  [params.cover]
    hiddenInList = true

[[params.socialIcons]]
  name = 'linkedin'
  url = 'https://www.linkedin.com/in/danielazurwerra/'

[[params.socialIcons]]
  name = 'youtube'
  url = 'https://www.youtube.com/@TheRaccoonWay'

[[menu.main]]
  name = 'Impressum'
  url = '/impressum/'
  weight = 20
